[package]
name = "vanityssh-rust"
version = "0.1.0"
edition = "2021"
description = "Generate SSH key pairs whose public keys match a user-specified regex pattern"
authors = ["kengggg"]
license = "MIT"
repository = "https://github.com/opemdream/vanityssh-rust"
keywords = ["ssh", "ed25519", "key-generation", "vanity", "cryptography"]
categories = ["command-line-utilities", "cryptography"]

[dependencies]
ed25519-dalek = "2"
rand = "0.9.3"
regex = "1.10.2"
anyhow = "1.0.89"
thiserror = "2.0.12"
indicatif = "0.17.8"
chrono = "0.4.38"
base64 = "0.22.1"
byteorder = "1.4.3"
hex = "0.4.3"
num_cpus = "1.16.0"
crossbeam = "0.8.4"
crossbeam-channel = "0.5.13"

[dev-dependencies]
assert_cmd = "2.0.10"
predicates = "3.0.3"
tempfile = "3.6.0"